// <auto-generated />
using System;
using Matchmaking.Migrations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matchmaking.Migrations.Data.Migrations
{
    [DbContext(typeof(MatchmakingDbContext))]
    [Migration("20251028153924_AddMatchReservations")]
    partial class AddMatchReservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matchmaking.Models.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<int>("SupportedInputs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.MatchReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Present")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PresentChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Registered")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RegisteredChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.PlatformGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("Group")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlaylistType")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LateJoinTicketId")
                        .HasColumnType("uuid");

                    b.Property<int>("OriginalInput")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Party")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Regions")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("SelectedInput")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LateJoinTicketId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Match", b =>
                {
                    b.HasOne("Matchmaking.Models.Domain.PlatformGroup", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.MatchReservation", b =>
                {
                    b.HasOne("Matchmaking.Models.Domain.Match", "Match")
                        .WithMany("Reservations")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matchmaking.Models.Domain.Ticket", "Ticket")
                        .WithOne("Reservation")
                        .HasForeignKey("Matchmaking.Models.Domain.MatchReservation", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Scenario", b =>
                {
                    b.HasOne("Matchmaking.Models.Domain.Playlist", "Playlist")
                        .WithMany("Scenarios")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Ticket", b =>
                {
                    b.HasOne("Matchmaking.Models.Domain.Ticket", "LateJoinTicket")
                        .WithMany("ChildTickets")
                        .HasForeignKey("LateJoinTicketId");

                    b.Navigation("LateJoinTicket");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Match", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Playlist", b =>
                {
                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("Matchmaking.Models.Domain.Ticket", b =>
                {
                    b.Navigation("ChildTickets");

                    b.Navigation("Reservation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
